/**
 * Copyright 2026-present Coinbase Global, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package allocations

import (
	"encoding/json"
	"fmt"

	"github.com/coinbase-samples/prime-cli/utils"
	"github.com/coinbase-samples/prime-sdk-go/allocations"
	"github.com/coinbase-samples/prime-sdk-go/model"

	"github.com/spf13/cobra"
)

var createNetAllocationCmd = &cobra.Command{
	Use:   "create-net",
	Short: "Creates a net portfolio allocation",
	RunE: func(cmd *cobra.Command, args []string) error {
		client, err := utils.GetClientFromEnv()
		if err != nil {
			return fmt.Errorf("failed to initialize client: %w", err)
		}

		allocationsService := allocations.NewAllocationsService(client)

		orderIds, err := cmd.Flags().GetStringArray(utils.OrderIdsFlag)
		if err != nil {
			return fmt.Errorf("cannot get order ids: %w", err)
		}

		allocationLegsJson, err := cmd.Flags().GetString(utils.AllocationLegsFlag)
		if err != nil {
			return fmt.Errorf("cannot get allocation legs: %w", err)
		}

		var allocationLegs []*model.AllocationLeg
		if err := json.Unmarshal([]byte(allocationLegsJson), &allocationLegs); err != nil {
			return fmt.Errorf("invalid allocation legs format: %w", err)
		}

		nettingId := utils.GetFlagStringValue(cmd, utils.NettingIdFlag)
		if len(nettingId) == 0 {
			idem := utils.GetFlagStringValue(cmd, utils.IdempotencyKeyFlag)
			if len(idem) == 0 {
				idem = utils.NewUuidStr()
			} else if err := utils.ValidateUUID(idem); err != nil {
				return err
			}
			nettingId = idem
		}

		ctx, cancel := utils.GetContextWithTimeout()
		defer cancel()

		request := &allocations.CreatePortfolioNetAllocationsRequest{
			NettingId:                       nettingId,
			SourcePortfolioId:               utils.GetFlagStringValue(cmd, utils.SourcePortfolioIdFlag),
			ProductId:                       utils.GetFlagStringValue(cmd, utils.ProductIdFlag),
			OrderIds:                        orderIds,
			AllocationLegs:                  allocationLegs,
			SizeType:                        utils.GetFlagStringValue(cmd, utils.SizeTypeFlag),
			RemainderDestinationPortfolioId: utils.GetFlagStringValue(cmd, utils.RemainderDestPortfolioIdFlag),
		}

		response, err := allocationsService.CreatePortfolioNetAllocations(ctx, request)
		if err != nil {
			return fmt.Errorf("cannot create net portfolio allocation: %w", err)
		}

		jsonResponse, err := utils.FormatResponseAsJson(cmd, response)
		if err != nil {
			return err
		}

		fmt.Println(jsonResponse)
		return nil
	},
}

func init() {
	Cmd.AddCommand(createNetAllocationCmd)

	createNetAllocationCmd.Flags().String(utils.NettingIdFlag, "", "ID for the net allocation. Autogenerated if blank")
	createNetAllocationCmd.Flags().String(utils.SourcePortfolioIdFlag, "", "ID of the source portfolio (Required)")
	createNetAllocationCmd.Flags().String(utils.ProductIdFlag, "", "ID of the product (Required)")
	createNetAllocationCmd.Flags().String(utils.SizeTypeFlag, "", "Size type of the allocation (Required)")
	createNetAllocationCmd.Flags().String(utils.RemainderDestPortfolioIdFlag, "", "ID of the remainder destination portfolio (Required)")
	createNetAllocationCmd.Flags().String(utils.AllocationLegsFlag, "", "JSON string of allocation legs (Required)")
	createNetAllocationCmd.Flags().StringArray(utils.OrderIdsFlag, []string{}, "List of order IDs (Required)")

	utils.AddIdempotencyKeyFlag(createNetAllocationCmd)

	createNetAllocationCmd.MarkFlagRequired(utils.SourcePortfolioIdFlag)
	createNetAllocationCmd.MarkFlagRequired(utils.ProductIdFlag)
	createNetAllocationCmd.MarkFlagRequired(utils.SizeTypeFlag)
	createNetAllocationCmd.MarkFlagRequired(utils.RemainderDestPortfolioIdFlag)
	createNetAllocationCmd.MarkFlagRequired(utils.AllocationLegsFlag)
	createNetAllocationCmd.MarkFlagRequired(utils.OrderIdsFlag)
}
